//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcunMedyaPortfolyoProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBAcunmedyaProject1Entities1 : DbContext
    {
        public DBAcunmedyaProject1Entities1()
            : base("name=DBAcunmedyaProject1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableAbout> TableAbout { get; set; }
        public virtual DbSet<TableCategory> TableCategory { get; set; }
        public virtual DbSet<TableContact> TableContact { get; set; }
        public virtual DbSet<TableEducation> TableEducation { get; set; }
        public virtual DbSet<TableJob> TableJob { get; set; }
        public virtual DbSet<TableServices> TableServices { get; set; }
        public virtual DbSet<TableSkill> TableSkill { get; set; }
        public virtual DbSet<TableSlider> TableSlider { get; set; }
        public virtual DbSet<TableTestimonial> TableTestimonial { get; set; }
        public virtual DbSet<TableMessage> TableMessage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableProject> TableProject { get; set; }
    }
}
